package com.ryx.card_compiler.utils;

/**
 * Created by hezhiqiang on 2018/11/21.
 */

public class Consts {
    public static final String SEPARATOR = "$$";
    public static final String PROJECT = "CardManager";
    public static final String PREFIX_OF_LOGGER = PROJECT + "::Compiler";
    public static final String METHOD_LOAD_INTO = "loadInto";
    public static final String NAME_OF_GROUP = PROJECT + SEPARATOR + "Group" + SEPARATOR;
    public static final String NAME_OF_ROOT = PROJECT + SEPARATOR + "Root" + SEPARATOR;
    public static final String PACKAGE_OF_GENERATE_FILE = "com.jianxin.android.card.cards"; //生成class的包名
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY ROUTERMANAGER.";


    // Options of processor
    public static final String KEY_MODULE_NAME = "MODULE_NAME";

    public static final String ANNOTATION_ROUTER_NAME = "com.ryx.card_annotation.annotation.Card";
    private static final String API_PACKAGE_NAME = "com.ryx.card_api";
    public static final String TEMPLITE_PACKAGE = ".template";
    public static final String ICARD_GROUP = API_PACKAGE_NAME + TEMPLITE_PACKAGE + ".ICardGroup";
    public static final String ICARD_ROOT = API_PACKAGE_NAME + TEMPLITE_PACKAGE + ".ICardRoot";
    // System interface
    public static final String MODEL = "com.jingyu.medium.widget.listpage.Model";
    public static final String PARCELABLE = "android.os.Parcelable";
    public static final String SERIALIZABLE = "java.io.Serializable";

}
